

-- First, remove the table if it exists
DROP TABLE IF EXISTS bookmark_data;

-- Create the table anew
CREATE TABLE bookmark_data (
  id INTEGER PRIMARY KEY GENERATED BY default as identity NOT NULL,
  title VARCHAR
(200) UNIQUE NOT NULL,
  summary TEXT,
  rating NUMERIC,
  url_link TEXT UNIQUE NOT NULL,
  date_created DATE
);

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO bookmark_data
  (title, url_link)
VALUES
  ('Javascript', 'http://www.bookmarkurl1.com'),
  ('Postgres', 'http://www.bookmarkurl2.com'),
  ('CSS', 'http://www.bookmarkurl3.com'),
  ('HTML', 'http://www.bookmarkurl4.com'),
  ('React', 'http://www.bookmarkurl5.com'),
  ('Angular', 'http://www.bookmarkurl6.com'),
  ('Python', 'http://www.bookmarkurl7.com'),
  ('TypeScript', 'http://www.bookmarkurl8.com'),
  ('MongoDB', 'http://www.bookmarkurl9.com'),
  ('Vue', 'http://www.bookmarkurl10.com');