-- First, remove the table if it exists
DROP TABLE IF EXISTS customers;

-- Create the table anew
CREATE TABLE customers (
  id INTEGER PRIMARY KEY GENERATED BY default as identity,
  customer_name TEXT,
  phone VARCHAR
(30)
);

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO customers
    (customer_name, phone)
VALUES
    ('Sam', '555-1234'),
    ('Ham', '555-4321'),
    ('Ram', '555-5678');